### PR TITLE
#Renderer2

### PR DESCRIPTION
**Pull request by xgeo**
renderer: deprecated

### CODE REVIEW

**Comment by GabrielGil** [comment]
Is this library maintained and compatible with Angular 9? :S

**Comment by xgeo** [comment]
https://angular.io/api/core/Renderer2

I hope so x)

**Comment by GabrielGil** [comment]
Sorry @xgeo. I was referring to ngx-facebook itself. As it seems that since 2018 hasn't been updated, so I'm not sure that the latest published version will work.

**Comment by MickL** [comment]
There is already a fork but @jemys89 didnt make a PR out of it: https://github.com/jemys89/ngx-facebook

**Comment by nadeemse** [comment]
When you planning to merge PR for Renderer2. ?

**Pull request merged**
